### ISSUE TITLE
no implicit conversion of Fixnum into String (TypeError)

### ISSUE THREAD

**Issue by jitendravyas** [eloyesp/jekyll_ghost_importer#3]
OSX 10
![1 zsh o0afn](https://cloud.githubusercontent.com/assets/77309/5683521/9e97a6b0-984e-11e4-80e4-85e80d4fa168.jpg)

**Comment by eloyesp** [comment]
It seems to have an issue parsing the `published_at` info in a post. They might have changed (again) the format.

Can you that info somewhere to help debug? (chose a single post from the json file and copy it somewhere)

**Comment by eloyesp** [comment]
I close as there is no feedback, re-open it as needed.
