### ISSUE TITLE
Not compatible with 0.5.8?

### ISSUE THREAD

**Issue by MoriTanosuke** [eloyesp/jekyll_ghost_importer#4]
I tried to import an export file from Ghost 0.5.8 today and jekyll_ghost_importer comes up with the following error message:

    /var/lib/gems/1.9.1/gems/jekyll_ghost_importer-0.2.0/bin/jekyll_ghost_importer:20:in `parse': can't convert Fixnum into String (TypeError)
	from /var/lib/gems/1.9.1/gems/jekyll_ghost_importer-0.2.0/bin/jekyll_ghost_importer:20:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/jekyll_ghost_importer-0.2.0/bin/jekyll_ghost_importer:19:in `each'
	from /var/lib/gems/1.9.1/gems/jekyll_ghost_importer-0.2.0/bin/jekyll_ghost_importer:19:in `<top (required)>'
	from /usr/local/bin/jekyll_ghost_importer:23:in `load'
	from /usr/local/bin/jekyll_ghost_importer:23:in `<main>'

Will you update the importer to the latest version?

**Comment by eloyesp** [comment]
@MoriTanosuke I can do it, but I would need a sample backup file, can you provide one?

**Comment by cwhitey** [comment]
Hi there,

I have the same problem. Here's a simple sample backup file with two published blog posts and one draft blog post.

    {"db":[{"meta":{"exported_on":1424346829618,"version":"003"},"data":{"posts":[{"id":1,"uuid":"ccb64228-dfbd-49e6-a02f-f4cf4651c4fd","title":"Welcome to Ghost","slug":"welcome-to-ghost","markdown":"You're live! Nice. We've put together a little post to introduce you to the Ghost editor and get you started. You can manage your content by signing in to the admin area at `<your blog URL>/ghost/`. When you arrive, you can select this post from a list on the left and see a preview of it on the right. Click the little pencil icon at the top of the preview to edit this post and read the next section!\n\n## Getting Started\n\nGhost uses something called Markdown for writing. Essentially, it's a shorthand way to manage your post formatting as you write!\n\nWriting in Markdown is really easy. In the left hand panel of Ghost, you simply write as you normally would. Where appropriate, you can use *shortcuts* to **style** your content. For example, a list:\n\n* Item number one\n* Item number two\n    * A nested item\n* A final item\n\nor with numbers!\n\n1. Remember to buy some milk\n2. Drink the milk\n3. Tweet that I remembered to buy the milk, and drank it\n\n### Links\n\nWant to link to a source? No problem. If you paste in a URL, like http://ghost.org - it'll automatically be linked up. But if you want to customise your anchor text, you can do that too! Here's a link to [the Ghost website](http://ghost.org). Neat.\n\n### What about Images?\n\nImages work too! Already know the URL of the image you want to include in your article? Simply paste it in like this to make it show up:\n\n![The Ghost Logo](https://ghost.org/images/ghost.png)\n\nNot sure which image you want to use yet? That's ok too. Leave yourself a descriptive placeholder and keep writing. Come back later and drag and drop the image in to upload:\n\n![A bowl of bananas]\n\n\n### Quoting\n\nSometimes a link isn't enough, you want to quote someone on what they've said. It was probably very wisdomous. Is wisdomous a word? Find out in a future release when we introduce spellcheck! For now - it's definitely a word.\n\n> Wisdomous - it's definitely a word.\n\n### Working with Code\n\nGot a streak of geek? We've got you covered there, too. You can write inline `<code>` blocks really easily with back ticks. Want to show off something more comprehensive? 4 spaces of indentation gets you there.\n\n    .awesome-thing {\n        display: block;\n        width: 100%;\n    }\n\n### Ready for a Break? \n\nThrow 3 or more dashes down on any new line and you've got yourself a fancy new divider. Aw yeah.\n\n---\n\n### Advanced Usage\n\nThere's one fantastic secret about Markdown. If you want, you can write plain old HTML and it'll still work! Very flexible.\n\n<input type=\"text\" placeholder=\"I'm an input field!\" />\n\nThat should be enough to get you started. Have fun - and let us know what you think :)","html":"<p>You're live! Nice. We've put together a little post to introduce you to the Ghost editor and get you started. You can manage your content by signing in to the admin area at <code>&lt;your blog URL&gt;/ghost/</code>. When you arrive, you can select this post from a list on the left and see a preview of it on the right. Click the little pencil icon at the top of the preview to edit this post and read the next section!</p>\n\n<h2 id=\"gettingstarted\">Getting Started</h2>\n\n<p>Ghost uses something called Markdown for writing. Essentially, it's a shorthand way to manage your post formatting as you write!</p>\n\n<p>Writing in Markdown is really easy. In the left hand panel of Ghost, you simply write as you normally would. Where appropriate, you can use <em>shortcuts</em> to <strong>style</strong> your content. For example, a list:</p>\n\n<ul>\n<li>Item number one</li>\n<li>Item number two\n<ul><li>A nested item</li></ul></li>\n<li>A final item</li>\n</ul>\n\n<p>or with numbers!</p>\n\n<ol>\n<li>Remember to buy some milk  </li>\n<li>Drink the milk  </li>\n<li>Tweet that I remembered to buy the milk, and drank it</li>\n</ol>\n\n<h3 id=\"links\">Links</h3>\n\n<p>Want to link to a source? No problem. If you paste in a URL, like <a href=\"http://ghost.org\">http://ghost.org</a> - it'll automatically be linked up. But if you want to customise your anchor text, you can do that too! Here's a link to <a href=\"http://ghost.org\">the Ghost website</a>. Neat.</p>\n\n<h3 id=\"whataboutimages\">What about Images?</h3>\n\n<p>Images work too! Already know the URL of the image you want to include in your article? Simply paste it in like this to make it show up:</p>\n\n<p><img src=\"https://ghost.org/images/ghost.png\" alt=\"The Ghost Logo\" /></p>\n\n<p>Not sure which image you want to use yet? That's ok too. Leave yourself a descriptive placeholder and keep writing. Come back later and drag and drop the image in to upload:</p>\n\n<h3 id=\"quoting\">Quoting</h3>\n\n<p>Sometimes a link isn't enough, you want to quote someone on what they've said. It was probably very wisdomous. Is wisdomous a word? Find out in a future release when we introduce spellcheck! For now - it's definitely a word.</p>\n\n<blockquote>\n  <p>Wisdomous - it's definitely a word.</p>\n</blockquote>\n\n<h3 id=\"workingwithcode\">Working with Code</h3>\n\n<p>Got a streak of geek? We've got you covered there, too. You can write inline <code>&lt;code&gt;</code> blocks really easily with back ticks. Want to show off something more comprehensive? 4 spaces of indentation gets you there.</p>\n\n<pre><code>.awesome-thing {\n    display: block;\n    width: 100%;\n}\n</code></pre>\n\n<h3 id=\"readyforabreak\">Ready for a Break?</h3>\n\n<p>Throw 3 or more dashes down on any new line and you've got yourself a fancy new divider. Aw yeah.</p>\n\n<hr />\n\n<h3 id=\"advancedusage\">Advanced Usage</h3>\n\n<p>There's one fantastic secret about Markdown. If you want, you can write plain old HTML and it'll still work! Very flexible.</p>\n\n<p><input type=\"text\" placeholder=\"I'm an input field!\" /></p>\n\n<p>That should be enough to get you started. Have fun - and let us know what you think :)</p>","image":null,"featured":0,"page":0,"status":"published","language":"en_US","meta_title":null,"meta_description":null,"author_id":1,"created_at":1424346554951,"created_by":1,"updated_at":1424346554951,"updated_by":1,"published_at":1424346554966,"published_by":1},{"id":2,"uuid":"287617c1-572e-43e1-8a3c-f7ad0d7bb71e","title":"new_post","slug":"new_post","markdown":"some test text\n\n    some code\n    \nfarewell","html":"<p>some test text</p>\n\n<pre><code>some code\n</code></pre>\n\n<p>farewell</p>","image":null,"featured":0,"page":0,"status":"published","language":"en_US","meta_title":null,"meta_description":null,"author_id":1,"created_at":1424346744945,"created_by":1,"updated_at":1424346784919,"updated_by":1,"published_at":1424346784919,"published_by":1},{"id":3,"uuid":"7beab6be-116a-45da-8a0d-7143ef74f952","title":"test draft","slug":"test-draft","markdown":"some text for a draft\n\n    draft code\n    \n    \nend","html":"<p>some text for a draft</p>\n\n<pre><code>draft code\n</code></pre>\n\n<p>end</p>","image":null,"featured":0,"page":0,"status":"draft","language":"en_US","meta_title":null,"meta_description":null,"author_id":1,"created_at":1424346793572,"created_by":1,"updated_at":1424346812457,"updated_by":1,"published_at":null,"published_by":null}],"users":[{"id":1,"uuid":"6a013e8f-24d3-4c77-901a-7e57f6537f47","name":"test test2","slug":"test","password":"some_password","email":"my_email","image":null,"cover":null,"bio":null,"website":null,"location":null,"accessibility":null,"status":"active","language":"en_US","meta_title":null,"meta_description":null,"last_login":1424346712870,"created_at":1424346562473,"created_by":1,"updated_at":1424346712870,"updated_by":1}],"roles":[{"id":1,"uuid":"b89fb85f-5f48-4740-90b9-f6c649ac87b9","name":"Administrator","description":"Administrators","created_at":1424346554967,"created_by":1,"updated_at":1424346554967,"updated_by":1},{"id":2,"uuid":"215af150-9e04-44f9-80db-9d185b24d44d","name":"Editor","description":"Editors","created_at":1424346554967,"created_by":1,"updated_at":1424346554967,"updated_by":1},{"id":3,"uuid":"fa683528-26e7-42f2-8d29-c5a07977030a","name":"Author","description":"Authors","created_at":1424346554968,"created_by":1,"updated_at":1424346554968,"updated_by":1},{"id":4,"uuid":"504cfee4-1b2c-4fb4-85ce-ed70eea8d32f","name":"Owner","description":"Blog Owner","created_at":1424346554968,"created_by":1,"updated_at":1424346554968,"updated_by":1}],"roles_users":[{"id":1,"role_id":4,"user_id":1}],"permissions":[{"id":1,"uuid":"e510978c-1f8a-45f6-b328-097b15d50e4c","name":"Export database","object_type":"db","action_type":"exportContent","object_id":null,"created_at":1424346555515,"created_by":1,"updated_at":1424346555515,"updated_by":1},{"id":2,"uuid":"88b0a3ad-fbdf-46be-aecd-369528b41498","name":"Import database","object_type":"db","action_type":"importContent","object_id":null,"created_at":1424346555598,"created_by":1,"updated_at":1424346555598,"updated_by":1},{"id":3,"uuid":"2f3485c9-0121-43c0-a863-7901063e7a7d","name":"Delete all content","object_type":"db","action_type":"deleteAllContent","object_id":null,"created_at":1424346555661,"created_by":1,"updated_at":1424346555661,"updated_by":1},{"id":4,"uuid":"7f6c6cc8-2ef7-4c5f-92bf-4dc4825d1405","name":"Send mail","object_type":"mail","action_type":"send","object_id":null,"created_at":1424346555723,"created_by":1,"updated_at":1424346555723,"updated_by":1},{"id":5,"uuid":"1ae6f067-8499-435a-a28c-a4180b25e7a3","name":"Browse notifications","object_type":"notification","action_type":"browse","object_id":null,"created_at":1424346555786,"created_by":1,"updated_at":1424346555786,"updated_by":1},{"id":6,"uuid":"bd0c1bee-b9ca-46ed-ab21-721fc9f48fd0","name":"Add notifications","object_type":"notification","action_type":"add","object_id":null,"created_at":1424346555853,"created_by":1,"updated_at":1424346555853,"updated_by":1},{"id":7,"uuid":"75b5ce09-f8a2-4907-94be-a6dc22523f58","name":"Delete notifications","object_type":"notification","action_type":"destroy","object_id":null,"created_at":1424346555917,"created_by":1,"updated_at":1424346555917,"updated_by":1},{"id":8,"uuid":"2b7ba557-1247-47e9-9d4b-14aba2f1aea2","name":"Browse posts","object_type":"post","action_type":"browse","object_id":null,"created_at":1424346555980,"created_by":1,"updated_at":1424346555980,"updated_by":1},{"id":9,"uuid":"3de67fbf-1e7f-490a-ae85-cefec8cfe385","name":"Read posts","object_type":"post","action_type":"read","object_id":null,"created_at":1424346556044,"created_by":1,"updated_at":1424346556044,"updated_by":1},{"id":10,"uuid":"f43b6153-2f68-4a58-b3b1-91abb0183a8a","name":"Edit posts","object_type":"post","action_type":"edit","object_id":null,"created_at":1424346556114,"created_by":1,"updated_at":1424346556114,"updated_by":1},{"id":11,"uuid":"0be0271a-8a46-45f8-a2a8-57046268acd5","name":"Add posts","object_type":"post","action_type":"add","object_id":null,"created_at":1424346556222,"created_by":1,"updated_at":1424346556222,"updated_by":1},{"id":12,"uuid":"760f64eb-48b2-4792-9b4c-9e6db0dd9bd8","name":"Delete posts","object_type":"post","action_type":"destroy","object_id":null,"created_at":1424346556285,"created_by":1,"updated_at":1424346556285,"updated_by":1},{"id":13,"uuid":"42d88cdf-05ec-46f8-8bd8-981c58e5bde9","name":"Browse settings","object_type":"setting","action_type":"browse","object_id":null,"created_at":1424346556348,"created_by":1,"updated_at":1424346556348,"updated_by":1},{"id":14,"uuid":"c28287d8-bdba-4f03-ad0d-f892cca0d122","name":"Read settings","object_type":"setting","action_type":"read","object_id":null,"created_at":1424346556412,"created_by":1,"updated_at":1424346556412,"updated_by":1},{"id":15,"uuid":"1bbb077b-9340-4f7c-a28d-2c13f97f48b2","name":"Edit settings","object_type":"setting","action_type":"edit","object_id":null,"created_at":1424346556489,"created_by":1,"updated_at":1424346556489,"updated_by":1},{"id":16,"uuid":"065d3fc3-a68f-459e-8447-15a9525cc8cb","name":"Generate slugs","object_type":"slug","action_type":"generate","object_id":null,"created_at":1424346556550,"created_by":1,"updated_at":1424346556550,"updated_by":1},{"id":17,"uuid":"380a547d-f200-4efd-8549-0e58e46f473a","name":"Browse tags","object_type":"tag","action_type":"browse","object_id":null,"created_at":1424346556614,"created_by":1,"updated_at":1424346556614,"updated_by":1},{"id":18,"uuid":"b54d1297-414a-4ddd-a4cc-413001634b34","name":"Read tags","object_type":"tag","action_type":"read","object_id":null,"created_at":1424346556678,"created_by":1,"updated_at":1424346556678,"updated_by":1},{"id":19,"uuid":"80560db1-8d7a-4fd4-95cc-bd947f9817f3","name":"Edit tags","object_type":"tag","action_type":"edit","object_id":null,"created_at":1424346556740,"created_by":1,"updated_at":1424346556740,"updated_by":1},{"id":20,"uuid":"54c3f98c-5f0f-4831-a62c-421076cc1b61","name":"Add tags","object_type":"tag","action_type":"add","object_id":null,"created_at":1424346556802,"created_by":1,"updated_at":1424346556802,"updated_by":1},{"id":21,"uuid":"82dd7530-7425-487f-b9ed-a31c9b95ab91","name":"Delete tags","object_type":"tag","action_type":"destroy","object_id":null,"created_at":1424346556865,"created_by":1,"updated_at":1424346556865,"updated_by":1},{"id":22,"uuid":"649266df-695f-4210-b13c-3f2e106cebf7","name":"Browse themes","object_type":"theme","action_type":"browse","object_id":null,"created_at":1424346556927,"created_by":1,"updated_at":1424346556927,"updated_by":1},{"id":23,"uuid":"f7a0a7a5-2a8e-4bce-870a-ab58dc54ff4c","name":"Edit themes","object_type":"theme","action_type":"edit","object_id":null,"created_at":1424346556988,"created_by":1,"updated_at":1424346556988,"updated_by":1},{"id":24,"uuid":"324010fa-95ac-448b-ae61-b547442f1893","name":"Browse users","object_type":"user","action_type":"browse","object_id":null,"created_at":1424346557049,"created_by":1,"updated_at":1424346557049,"updated_by":1},{"id":25,"uuid":"d9595469-f9b0-4fe8-aabc-14f3ce3ffcdf","name":"Read users","object_type":"user","action_type":"read","object_id":null,"created_at":1424346557114,"created_by":1,"updated_at":1424346557114,"updated_by":1},{"id":26,"uuid":"295ae916-0477-4a91-a69f-2339dedf694e","name":"Edit users","object_type":"user","action_type":"edit","object_id":null,"created_at":1424346557176,"created_by":1,"updated_at":1424346557176,"updated_by":1},{"id":27,"uuid":"1370e192-c539-4403-85c1-99d2d82383c9","name":"Add users","object_type":"user","action_type":"add","object_id":null,"created_at":1424346557242,"created_by":1,"updated_at":1424346557242,"updated_by":1},{"id":28,"uuid":"4518eb77-d484-4f89-a548-402280c2efd4","name":"Delete users","object_type":"user","action_type":"destroy","object_id":null,"created_at":1424346557303,"created_by":1,"updated_at":1424346557303,"updated_by":1},{"id":29,"uuid":"95d3432f-8699-4a5f-9cc7-67dbe2389ba2","name":"Assign a role","object_type":"role","action_type":"assign","object_id":null,"created_at":1424346557368,"created_by":1,"updated_at":1424346557368,"updated_by":1},{"id":30,"uuid":"b4f8ee6e-1eea-4445-99b2-61c1b870bbbb","name":"Browse roles","object_type":"role","action_type":"browse","object_id":null,"created_at":1424346557430,"created_by":1,"updated_at":1424346557430,"updated_by":1}],"permissions_users":[],"permissions_roles":[{"id":1,"role_id":1,"permission_id":1},{"id":2,"role_id":1,"permission_id":2},{"id":3,"role_id":1,"permission_id":3},{"id":4,"role_id":1,"permission_id":4},{"id":5,"role_id":1,"permission_id":5},{"id":6,"role_id":1,"permission_id":6},{"id":7,"role_id":1,"permission_id":7},{"id":8,"role_id":1,"permission_id":8},{"id":9,"role_id":1,"permission_id":9},{"id":10,"role_id":1,"permission_id":10},{"id":11,"role_id":1,"permission_id":11},{"id":12,"role_id":1,"permission_id":12},{"id":13,"role_id":1,"permission_id":13},{"id":14,"role_id":1,"permission_id":14},{"id":15,"role_id":1,"permission_id":15},{"id":16,"role_id":1,"permission_id":16},{"id":17,"role_id":1,"permission_id":17},{"id":18,"role_id":1,"permission_id":18},{"id":19,"role_id":1,"permission_id":19},{"id":20,"role_id":1,"permission_id":20},{"id":21,"role_id":1,"permission_id":21},{"id":22,"role_id":1,"permission_id":22},{"id":23,"role_id":1,"permission_id":23},{"id":24,"role_id":1,"permission_id":24},{"id":25,"role_id":1,"permission_id":25},{"id":26,"role_id":1,"permission_id":26},{"id":27,"role_id":1,"permission_id":27},{"id":28,"role_id":1,"permission_id":28},{"id":29,"role_id":1,"permission_id":29},{"id":30,"role_id":1,"permission_id":30},{"id":31,"role_id":2,"permission_id":8},{"id":32,"role_id":2,"permission_id":9},{"id":33,"role_id":2,"permission_id":10},{"id":34,"role_id":2,"permission_id":11},{"id":35,"role_id":2,"permission_id":12},{"id":36,"role_id":2,"permission_id":13},{"id":37,"role_id":2,"permission_id":14},{"id":38,"role_id":2,"permission_id":16},{"id":39,"role_id":2,"permission_id":17},{"id":40,"role_id":2,"permission_id":18},{"id":41,"role_id":2,"permission_id":19},{"id":42,"role_id":2,"permission_id":20},{"id":43,"role_id":2,"permission_id":21},{"id":44,"role_id":2,"permission_id":24},{"id":45,"role_id":2,"permission_id":25},{"id":46,"role_id":2,"permission_id":26},{"id":47,"role_id":2,"permission_id":27},{"id":48,"role_id":2,"permission_id":28},{"id":49,"role_id":2,"permission_id":29},{"id":50,"role_id":2,"permission_id":30},{"id":51,"role_id":3,"permission_id":8},{"id":52,"role_id":3,"permission_id":9},{"id":53,"role_id":3,"permission_id":11},{"id":54,"role_id":3,"permission_id":13},{"id":55,"role_id":3,"permission_id":14},{"id":56,"role_id":3,"permission_id":16},{"id":57,"role_id":3,"permission_id":17},{"id":58,"role_id":3,"permission_id":18},{"id":59,"role_id":3,"permission_id":20},{"id":60,"role_id":3,"permission_id":24},{"id":61,"role_id":3,"permission_id":25},{"id":62,"role_id":3,"permission_id":30}],"permissions_apps":[],"settings":[{"id":1,"uuid":"fc42ea87-b9e8-4ab2-9005-957f089fee42","key":"databaseVersion","value":"003","type":"core","created_at":1424346562618,"created_by":1,"updated_at":1424346562618,"updated_by":1},{"id":2,"uuid":"ba69d8c4-cbce-4165-81a1-1b1ddbc511ee","key":"dbHash","value":"85d74e8d-072a-492e-b2a6-1cf9ac849909","type":"core","created_at":1424346562706,"created_by":1,"updated_at":1424346564154,"updated_by":1},{"id":3,"uuid":"c095b721-0e6f-4e29-8279-15ccab085e07","key":"nextUpdateCheck","value":"1424433033","type":"core","created_at":1424346562706,"created_by":1,"updated_at":1424346632886,"updated_by":1},{"id":4,"uuid":"9a4a53d4-5d6a-48f6-a0b6-c2421f2fa700","key":"displayUpdateNotification","value":null,"type":"core","created_at":1424346562706,"created_by":1,"updated_at":1424346562706,"updated_by":1},{"id":5,"uuid":"8e4ee9ba-d3b2-45aa-9bb4-15f97e3a8fa9","key":"title","value":"cwhitey","type":"blog","created_at":1424346562707,"created_by":1,"updated_at":1424346662398,"updated_by":1},{"id":6,"uuid":"b3c3e01e-8439-40a8-aea1-4157dee234d0","key":"description","value":"Thoughts, stories and ideas.","type":"blog","created_at":1424346562707,"created_by":1,"updated_at":1424346662399,"updated_by":1},{"id":7,"uuid":"382c7007-f222-4a45-8ef2-54edce39557a","key":"email","value":"jamescrysis@gmail.com","type":"blog","created_at":1424346562707,"created_by":1,"updated_at":1424346662397,"updated_by":1},{"id":8,"uuid":"2d5edfd1-2bf5-4f1f-83f3-2413f9c859ec","key":"logo","value":"","type":"blog","created_at":1424346562707,"created_by":1,"updated_at":1424346562707,"updated_by":1},{"id":9,"uuid":"545b78e1-837a-4209-b46b-8fcb9633cb8f","key":"cover","value":"","type":"blog","created_at":1424346562708,"created_by":1,"updated_at":1424346562708,"updated_by":1},{"id":10,"uuid":"09210276-caf9-499e-b1ee-eec432570cb3","key":"defaultLang","value":"en_US","type":"blog","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":11,"uuid":"0dc6c8d6-857c-434b-914a-092c1c13d937","key":"postsPerPage","value":"5","type":"blog","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":12,"uuid":"7808cf40-348c-44a3-8f8e-13c7980184c7","key":"forceI18n","value":"true","type":"blog","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":13,"uuid":"85139e2f-73d2-4c3e-8830-4a20f05797c1","key":"permalinks","value":"/:slug/","type":"blog","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":14,"uuid":"c6109fe3-eb56-412d-8e28-a636ab5ab74e","key":"ghost_head","value":"","type":"blog","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":15,"uuid":"0a234c9f-258e-42fa-a539-8e075c900667","key":"ghost_foot","value":"","type":"blog","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":16,"uuid":"127ac7d4-eb66-47d3-bf6b-7a8fff4a1695","key":"labs","value":"{}","type":"blog","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":17,"uuid":"4db15ed3-0a16-4448-a905-d0454e35247b","key":"activeApps","value":"[]","type":"app","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1},{"id":18,"uuid":"8848a8c5-f441-47cd-be35-c32d7c4e1cbd","key":"installedApps","value":"[]","type":"app","created_at":1424346562710,"created_by":1,"updated_at":1424346564156,"updated_by":1},{"id":19,"uuid":"4b37a91b-1108-49ad-9ec6-7e664fc90c4d","key":"activeTheme","value":"casper","type":"theme","created_at":1424346562709,"created_by":1,"updated_at":1424346562709,"updated_by":1}],"tags":[{"id":1,"uuid":"befcb6c7-c777-4a65-a272-6e2577cade61","name":"Getting Started","slug":"getting-started","description":null,"image":null,"hidden":0,"parent_id":null,"meta_title":null,"meta_description":null,"created_at":1424346554967,"created_by":1,"updated_at":1424346554967,"updated_by":1}],"posts_tags":[{"id":1,"post_id":1,"tag_id":1}],"apps":[],"app_settings":[],"app_fields":[]}}]}

**Comment by eloyesp** [comment]
Thanks @cwhitey I will work on it ASAP.

**Comment by eloyesp** [comment]
@cwhitey It should be working with version 0.3.0, thanks for your help.

**Comment by cwhitey** [comment]
Great! Thanks @eloyesp, that worked for me!
