### ISSUE TITLE
Does not preserve Ghost tags - Ghost v0.5.8

### ISSUE THREAD

**Issue by cwhitey** [eloyesp/jekyll_ghost_importer#5]
Hi,

I have no idea how easy this is for you to implement, but it would be really nice if Ghost tags for individual posts were preserved and added to the .markdown files. 
All I get in the .markdown file headers is the 'layout', 'title', and 'date' fields.

Thanks!

**Comment by jcbsnd** [comment]
+1

**Comment by eloyesp** [comment]
It's implemented in v0.4 :)
